# Generated by Django 2.0.5 on 2020-01-17 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0003_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_type', models.CharField(max_length=10)),
                ('ap_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=250)),
                ('house_title', models.CharField(max_length=500)),
                ('contact', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Apartment',
        ),
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.AddField(
            model_name='appart',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.House'),
        ),
    ]
