# Generated by Django 2.0.5 on 2020-01-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0004_auto_20200117_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='Apartment_pics'),
        ),
    ]
